### ISSUE TITLE
Setting input stream after download button creation

### ISSUE THREAD

**Issue by scrmtrey91** [stefanuebe/vaadin-lazy-download-button#11]
Hello.

Download button working super great when you set filename callback and inputstream callback and constructor.

But when i set filename and inputstream callback after the button was created, the download does not occur.

Example:

1)
```java
 private final LazyDownloadButton downloadButton = new LazyDownloadButton(VaadinIcon.FILE_ZIP.create());
```

2)
```java
 downloadButton.setFileNameCallback(() -> filename);
 downloadButton.setInputStreamCallback(() -> new ByteArrayInputStream(byte array content));
```

Reason: looks like the constructor with only ICON does not add click listener for downloading

Update2 ():
1) 
```java
   private LazyDownloadButton downloadButton = new LazyDownloadButton(VaadinIcon.FILE_ZIP.create(), null, null);
```

2)
```java
 downloadButton.setFileNameCallback(() -> filename);
 downloadButton.setInputStreamCallback(() -> new ByteArrayInputStream(byte array content));
```

Error:
```stacktrace
java.lang.NullPointerException: File name callback must not be null
	at java.util.Objects.requireNonNull(Objects.java:233) ~[?:?]
	at org.vaadin.stefan.LazyDownloadButton.lambda$null$3(LazyDownloadButton.java:100) ~[lazy-download-button-1.0.0.jar:1.0.0]
```

Vaadin 23.2.3, 23.1.10
Java 17

**Comment by javier-godoy** [comment]
Calling `setFileNameCallback`/`setInputStreamCallback` after the component has been instantiated does nothing, because the click listener references the captured parameter `fileNameCallback` which shadows `this.fileNameCallback`. In addition, the only constructor that actually configures the clickListener is `LazyDownloadButton(String, Component, Supplier<String>, InputStreamFactory)`, the other constructors are broken.

**Comment by stefanuebe** [comment]
Hi, I am currently on paternal leave, so not sure when I will have time to fix this. Feel free to create a PR, then I can merge and update that
